# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'com_spec1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spec1(object):
    def setupUi(self, spec1):
        spec1.setObjectName("spec1")
        spec1.resize(1000, 800)
        self.stackedWidget = QtWidgets.QStackedWidget(spec1)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 0, 771, 801))
        self.stackedWidget.setStyleSheet("background-color: rgb(199, 7, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Spec = QtWidgets.QLabel(self.page)
        self.Spec.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.Spec.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Spec.setObjectName("Spec")
        self.processor = QtWidgets.QLabel(self.page)
        self.processor.setGeometry(QtCore.QRect(30, 60, 201, 21))
        self.processor.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.processor.setObjectName("processor")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 90, 501, 21))
        self.label.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 171, 41))
        self.label_2.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 431, 31))
        self.label_3.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 101, 31))
        self.label_4.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 351, 16))
        self.label_5.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 101, 41))
        self.label_6.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(30, 300, 201, 31))
        self.label_7.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(30, 280, 271, 16))
        self.label_8.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 221, 101))
        self.label_9.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(0, 450, 801, 16))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Spec_2 = QtWidgets.QLabel(self.page)
        self.Spec_2.setGeometry(QtCore.QRect(40, 470, 161, 31))
        self.Spec_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Spec_2.setObjectName("Spec_2")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(40, 520, 181, 41))
        self.label_10.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(40, 580, 181, 51))
        self.label_11.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(40, 640, 171, 91))
        self.label_12.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(240, 530, 71, 21))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(240, 600, 101, 21))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(240, 670, 101, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page)
        self.label_16.setGeometry(QtCore.QRect(390, 520, 121, 41))
        self.label_16.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(390, 580, 141, 41))
        self.label_17.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(390, 650, 151, 51))
        self.label_18.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page)
        self.label_19.setGeometry(QtCore.QRect(550, 590, 101, 21))
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page)
        self.label_20.setGeometry(QtCore.QRect(550, 530, 101, 21))
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page)
        self.label_21.setGeometry(QtCore.QRect(550, 660, 101, 21))
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.close_spec_1 = QtWidgets.QPushButton(self.page)
        self.close_spec_1.setGeometry(QtCore.QRect(660, 750, 81, 31))
        self.close_spec_1.setStyleSheet("background-color: rgb(171, 171, 171);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.close_spec_1.setObjectName("close_spec_1")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.label_22 = QtWidgets.QLabel(spec1)
        self.label_22.setGeometry(QtCore.QRect(50, 490, 121, 41))
        self.label_22.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(spec1)
        self.label_23.setGeometry(QtCore.QRect(0, 260, 221, 181))
        self.label_23.setStyleSheet("image: url(:/res/img/4zu3_Dell_Inspiron_15_3501.jpg);")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/res/image/4zu3_Dell_Inspiron_15_3501.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")

        self.retranslateUi(spec1)
        self.close_spec_1.clicked.connect(spec1.close)
        QtCore.QMetaObject.connectSlotsByName(spec1)

    def retranslateUi(self, spec1):
        _translate = QtCore.QCoreApplication.translate
        spec1.setWindowTitle(_translate("spec1", "spec1"))
        self.Spec.setText(_translate("spec1", "Specifications"))
        self.processor.setText(_translate("spec1", "Processor"))
        self.label.setText(_translate("spec1", "- 11th Generation Intel Core i5-11320H Processor (8MB Cache,up to 4.5 GHz)"))
        self.label_2.setText(_translate("spec1", "Video card"))
        self.label_3.setText(_translate("spec1", "- Intel Iris Xe Graphics with shared graphics memory"))
        self.label_4.setText(_translate("spec1", "Memory"))
        self.label_5.setText(_translate("spec1", "- 8GB , 2 x 4GB,DDR4,3200 MHz,dual-channel"))
        self.label_6.setText(_translate("spec1", "Hard Drive"))
        self.label_7.setText(_translate("spec1", "Dimension and weight"))
        self.label_8.setText(_translate("spec1", "- 256GB M.2 PCIe NVMe solid state drive"))
        self.label_9.setText(_translate("spec1", "-Height (front): 14.6 mm (0.57\")\n"
"-Height (rear): 17.99 mm (0.71\")\n"
"-Width: 356.06 mm (14.02\")\n"
"-Depth: 228.9 mm (9.01\")\n"
"-Starting Weight: 1.633 kg (3.6 lb)"))
        self.Spec_2.setText(_translate("spec1", "Accessorries"))
        self.label_10.setText(_translate("spec1", "Dell Wired Mouse with \n"
"Fingerprint Reader - MS819"))
        self.label_11.setText(_translate("spec1", "Alienware Wired/Wireless \n"
"Gaming Mouse | AW610M"))
        self.label_12.setText(_translate("spec1", "ALIENWARE RGB \n"
"MECHANICAL \n"
"GAMING KEYBOARD\n"
"| AW410K"))
        self.label_13.setText(_translate("spec1", "+ RM174"))
        self.label_14.setText(_translate("spec1", "+ RM 411.09"))
        self.label_15.setText(_translate("spec1", "+ RM 631.50"))
        self.label_16.setText(_translate("spec1", "Dell Adapter \n"
"- USB-C to VGA"))
        self.label_17.setText(_translate("spec1", "Dell Adaptor- USB-C \n"
"to DisplayPort"))
        self.label_18.setText(_translate("spec1", "Dell Adapter - USB 3.0 \n"
"to Ethernet PXE Boot"))
        self.label_19.setText(_translate("spec1", "+ RM 162"))
        self.label_20.setText(_translate("spec1", "+ RM 201"))
        self.label_21.setText(_translate("spec1", "+ RM 158"))
        self.close_spec_1.setText(_translate("spec1", "Close"))
        self.label_22.setText(_translate("spec1", "Inspiron"))
from . import res_rc
