# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'com_spec3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spec_3(object):
    def setupUi(self, spec_3):
        spec_3.setObjectName("spec_3")
        spec_3.resize(1000, 800)
        self.stackedWidget = QtWidgets.QStackedWidget(spec_3)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 0, 771, 801))
        self.stackedWidget.setStyleSheet("background-color: rgb(199, 7, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Spec = QtWidgets.QLabel(self.page)
        self.Spec.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.Spec.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Spec.setObjectName("Spec")
        self.processor = QtWidgets.QLabel(self.page)
        self.processor.setGeometry(QtCore.QRect(30, 60, 201, 21))
        self.processor.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.processor.setObjectName("processor")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 90, 651, 21))
        self.label.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 171, 41))
        self.label_2.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 431, 31))
        self.label_3.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 101, 31))
        self.label_4.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 351, 16))
        self.label_5.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(30, 220, 101, 41))
        self.label_6.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(30, 290, 201, 31))
        self.label_7.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(30, 260, 271, 16))
        self.label_8.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(30, 320, 271, 151))
        self.label_9.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(0, 470, 801, 16))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Spec_2 = QtWidgets.QLabel(self.page)
        self.Spec_2.setGeometry(QtCore.QRect(40, 490, 161, 31))
        self.Spec_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Spec_2.setObjectName("Spec_2")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(40, 550, 181, 71))
        self.label_10.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(40, 650, 211, 61))
        self.label_12.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(260, 580, 101, 21))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(260, 670, 101, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.close_spec_1 = QtWidgets.QPushButton(self.page)
        self.close_spec_1.setGeometry(QtCore.QRect(660, 750, 81, 31))
        self.close_spec_1.setStyleSheet("background-color: rgb(171, 171, 171);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.close_spec_1.setObjectName("close_spec_1")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.label_22 = QtWidgets.QLabel(spec_3)
        self.label_22.setGeometry(QtCore.QRect(0, 470, 211, 121))
        self.label_22.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_14 = QtWidgets.QLabel(spec_3)
        self.label_14.setGeometry(QtCore.QRect(10, 290, 211, 161))
        self.label_14.setStyleSheet("image: url(:/res/img/M15.jpg);")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/res/image/M15.jpg"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")

        self.retranslateUi(spec_3)
        self.close_spec_1.clicked.connect(spec_3.close)
        QtCore.QMetaObject.connectSlotsByName(spec_3)

    def retranslateUi(self, spec_3):
        _translate = QtCore.QCoreApplication.translate
        spec_3.setWindowTitle(_translate("spec_3", "Dialog"))
        self.Spec.setText(_translate("spec_3", "Specifications"))
        self.processor.setText(_translate("spec_3", "Processor"))
        self.label.setText(_translate("spec_3", "- 11th Generation Intel® Core™ i7 11800H (8-Core, 24MB L3 Cache, up to 4.6GHz with Turbo Boost)"))
        self.label_2.setText(_translate("spec_3", "Video card"))
        self.label_3.setText(_translate("spec_3", "- NVIDIA® GeForce RTX™ 3060 6GB GDDR6"))
        self.label_4.setText(_translate("spec_3", "Memory"))
        self.label_5.setText(_translate("spec_3", "- 16 GB, 2 x 8 GB, DDR4, 3200 MHz, dual-channel"))
        self.label_6.setText(_translate("spec_3", "Hard Drive"))
        self.label_7.setText(_translate("spec_3", "Dimension and weight"))
        self.label_8.setText(_translate("spec_3", "- 512GB PCIe NVMe M.2 SSD"))
        self.label_9.setText(_translate("spec_3", "Height (Front): 0.508\" (12.9 mm) \n"
"| Height (Peak): 0.8996\" (22.85 mm) \n"
"| Height (Rear): 0.7579\" (19.25 mm) \n"
"|  Width: 14.02\" (356.2 mm) \n"
"| Depth: 10.73\" (272.5 mm) \n"
"| Lowest weight: 2.42 kgs (5.34lbs)* \n"
"| Maximum weight: 2.69 kgs (5.93lbs)"))
        self.Spec_2.setText(_translate("spec_3", "Accessorries"))
        self.label_10.setText(_translate("spec_3", "Alienware 510H 7.1 Gaming \n"
"Headset AW510H \n"
"- Dark Side of the Moon"))
        self.label_12.setText(_translate("spec_3", "Alienware 510H 7.1 Gaming \n"
"Headset AW510H - Lunar Light"))
        self.label_13.setText(_translate("spec_3", "+ RM 433.30"))
        self.label_15.setText(_translate("spec_3", "+ RM 436.80"))
        self.close_spec_1.setText(_translate("spec_3", "Close"))
        self.label_22.setText(_translate("spec_3", "M15 \n"
"Gaming laptop"))
from . import res_rc
