# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_spec_2(object):
    def setupUi(self, spec_2):
        spec_2.setObjectName("spec_2")
        spec_2.resize(1000, 800)
        self.stackedWidget = QtWidgets.QStackedWidget(spec_2)
        self.stackedWidget.setGeometry(QtCore.QRect(230, 0, 771, 801))
        self.stackedWidget.setStyleSheet("background-color: rgb(199, 7, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Spec = QtWidgets.QLabel(self.page)
        self.Spec.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.Spec.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Spec.setObjectName("Spec")
        self.processor = QtWidgets.QLabel(self.page)
        self.processor.setGeometry(QtCore.QRect(30, 60, 201, 21))
        self.processor.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.processor.setObjectName("processor")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(30, 90, 661, 21))
        self.label.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 171, 41))
        self.label_2.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 291, 31))
        self.label_3.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 101, 31))
        self.label_4.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 351, 16))
        self.label_5.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 101, 41))
        self.label_6.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(30, 300, 201, 31))
        self.label_7.setStyleSheet("font: 12pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(30, 270, 271, 16))
        self.label_8.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(30, 340, 251, 81))
        self.label_9.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(0, 450, 801, 16))
        self.line.setStyleSheet("color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Spec_2 = QtWidgets.QLabel(self.page)
        self.Spec_2.setGeometry(QtCore.QRect(40, 470, 161, 31))
        self.Spec_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-decoration: underline;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.Spec_2.setObjectName("Spec_2")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(40, 520, 181, 41))
        self.label_10.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(40, 580, 181, 51))
        self.label_11.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(40, 640, 191, 91))
        self.label_12.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(240, 530, 81, 21))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setGeometry(QtCore.QRect(240, 600, 101, 21))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(240, 670, 101, 21))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page)
        self.label_16.setGeometry(QtCore.QRect(390, 520, 171, 41))
        self.label_16.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(390, 580, 231, 41))
        self.label_17.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(390, 650, 181, 51))
        self.label_18.setStyleSheet("font: 9pt \"Nirmala UI Semilight\";\n"
"color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page)
        self.label_19.setGeometry(QtCore.QRect(640, 590, 111, 21))
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page)
        self.label_20.setGeometry(QtCore.QRect(640, 520, 101, 21))
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page)
        self.label_21.setGeometry(QtCore.QRect(640, 660, 101, 21))
        self.label_21.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.close_spec_1 = QtWidgets.QPushButton(self.page)
        self.close_spec_1.setGeometry(QtCore.QRect(660, 750, 81, 31))
        self.close_spec_1.setStyleSheet("background-color: rgb(171, 171, 171);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.close_spec_1.setObjectName("close_spec_1")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.label_22 = QtWidgets.QLabel(spec_2)
        self.label_22.setGeometry(QtCore.QRect(10, 470, 211, 111))
        self.label_22.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(spec_2)
        self.label_23.setGeometry(QtCore.QRect(0, 290, 221, 181))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap(":/res/image/G15.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")

        self.retranslateUi(spec_2)
        self.stackedWidget.setCurrentIndex(0)
        self.close_spec_1.clicked.connect(spec_2.close)
        QtCore.QMetaObject.connectSlotsByName(spec_2)

    def retranslateUi(self, spec_2):
        _translate = QtCore.QCoreApplication.translate
        spec_2.setWindowTitle(_translate("spec_2", "Dialog"))
        self.Spec.setText(_translate("spec_2", "Specifications"))
        self.processor.setText(_translate("spec_2", "Processor"))
        self.label.setText(_translate("spec_2", "- 11th Generation Intel® Core™ i7-11800H (24MB Cache, up to 4.6 GHz, 8 cores)"))
        self.label_2.setText(_translate("spec_2", "Video card"))
        self.label_3.setText(_translate("spec_2", "- NVIDIA® GeForce RTX™ 3050 Ti 4GB GDDR6"))
        self.label_4.setText(_translate("spec_2", "Memory"))
        self.label_5.setText(_translate("spec_2", "- 16 GB, 2 x 8 GB, DDR4, 3200 MHz, dual-channel"))
        self.label_6.setText(_translate("spec_2", "Hard Drive"))
        self.label_7.setText(_translate("spec_2", "Dimension and weight"))
        self.label_8.setText(_translate("spec_2", "- 512GB M.2 PCIe NVMe Solid State Drive"))
        self.label_9.setText(_translate("spec_2", "Height: 24.9mm (0.98\") | \n"
"Width: 357.26mm (14.06\") | \n"
"Depth: 272.83mm (10.74\") | \n"
"Starting Weight: 2.44 kg"))
        self.Spec_2.setText(_translate("spec_2", "Accessorries"))
        self.label_10.setText(_translate("spec_2", "Dell Alienware 25 Monitor \n"
"- AW2521H"))
        self.label_11.setText(_translate("spec_2", "Alienware 25 Gaming Monitor \n"
"- AW2521HF"))
        self.label_12.setText(_translate("spec_2", "Alienware 27 240Hz monitor \n"
"- AW2720HF\n"
"- AW2720HF"))
        self.label_13.setText(_translate("spec_2", "+ RM3319"))
        self.label_14.setText(_translate("spec_2", "+ RM2069"))
        self.label_15.setText(_translate("spec_2", "+ RM2299"))
        self.label_16.setText(_translate("spec_2", "Dell UltraSharp Webcam \n"
"- WB7022"))
        self.label_17.setText(_translate("spec_2", "Dell Premier ANC Wireless Headset \n"
"- WL7022"))
        self.label_18.setText(_translate("spec_2", "Dell Pro Wireless Headset \n"
"- WL5022"))
        self.label_19.setText(_translate("spec_2", "+ RM 1146.65"))
        self.label_20.setText(_translate("spec_2", "+ RM 867.36"))
        self.label_21.setText(_translate("spec_2", "+ RM 922.96"))
        self.close_spec_1.setText(_translate("spec_2", "Close"))
        self.label_22.setText(_translate("spec_2", "G15 \n"
"Gaming laptop"))
from . import res_rc
