# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Welcome(object):
    def setupUi(self, Welcome):
        Welcome.setObjectName("Welcome")
        Welcome.resize(1499, 935)
        self.centralwidget = QtWidgets.QWidget(Welcome)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 1551, 111))
        self.stackedWidget.setStyleSheet("background-color: rgb(199, 7, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(550, 30, 461, 41))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font:  18pt \"Microsoft YaHei UI\";")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.Next_store = QtWidgets.QPushButton(self.centralwidget)
        self.Next_store.setGeometry(QtCore.QRect(690, 650, 121, 51))
        self.Next_store.setObjectName("Next_store")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 250, 401, 361))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/res/image/welcome.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        Welcome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Welcome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1499, 26))
        self.menubar.setObjectName("menubar")
        Welcome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Welcome)
        self.statusbar.setObjectName("statusbar")
        Welcome.setStatusBar(self.statusbar)

        self.retranslateUi(Welcome)
        QtCore.QMetaObject.connectSlotsByName(Welcome)

    def retranslateUi(self, Welcome):
        _translate = QtCore.QCoreApplication.translate
        Welcome.setWindowTitle(_translate("Welcome", "MainWindow"))
        self.label_2.setText(_translate("Welcome", "Welcome to The Gaming Store!"))
        self.Next_store.setText(_translate("Welcome", "Enter"))
from . import res_rc
